# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FFXIVClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lore', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TANK', 'Tank'), ('DPS', 'Dps'), ('HEAL', 'Healer')], max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='ffxivclass',
            name='dng_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ffxivclass.RoleSelect'),
        ),
    ]
