# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffxivclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffxivclass',
            name='lore',
            field=models.TextField(null=True),
        ),
    ]
