# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ffxivclass', '0002_auto_20170104_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='ffxivclass',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ffxivclass',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
