# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ffxivclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expansion_name', models.CharField(choices=[('ARR', 'A Realm Reborn'), ('HW', 'Heavensward'), ('SB', 'Storm Blood')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FFXIVJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('lore', models.TextField(null=True)),
                ('icon', models.CharField(max_length=255, null=True)),
                ('available', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ffxivjob.Expansion')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ffxivclass.RoleSelect')),
            ],
        ),
    ]
