# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseclass',
            options={'verbose_name': 'Elenco Classe (Base)', 'verbose_name_plural': 'Elenco Classi (Base)'},
        ),
    ]
