# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_room', '0004_job_stat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basejob',
            options={'verbose_name': 'Elenco Job', 'verbose_name_plural': 'Elenco Jobs'},
        ),
        migrations.AlterField(
            model_name='basejob',
            name='basejobname',
            field=models.CharField(choices=[('Paladin', 'PLD'), ('Warrior', 'WAR'), ('Dark Knight', 'DRK'), ('Monk', 'MNK'), ('Dragoon', 'DRG'), ('Bard', 'BRD'), ('Machinist', 'MCH'), ('Ninja', 'NIN'), ('White Mage', 'WHM'), ('Black Mage', 'BLM'), ('Scholar', 'SCH'), ('Summoner', 'SMN'), ('Astrologian', 'AST')], max_length=40, verbose_name='Nome del Job'),
        ),
    ]
