# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-05 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_room', '0006_auto_20170105_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='icon',
            field=models.CharField(max_length=255, null=True, verbose_name='Icona'),
        ),
        migrations.AlterField(
            model_name='job',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Icona'),
        ),
    ]
